### ISSUE TITLE
With RollupJS: "Uncaught TypeError: MySwal.fire is not a function"

### ISSUE THREAD

**Issue by blacksmoke26** [sweetalert2/sweetalert2-react-content#79] opened 2019-02-22 05:19 UTC
Followed homepage example but leads to an error!

**Comment by zenflow** [comment] 2019-02-22 06:38
Seems to be working fine here: https://codesandbox.io/s/826xvvxrv2

Do you happen to be working with TypeScript? Is this a duplicate of #33?

If not, can you reproduce the error on https://codesandbox.io or https://codepen.io/ or https://jsfiddle.net/ or something like that?

**Comment by blacksmoke26** [comment] 2019-02-22 16:49
Well I am using RollupJS.

ReactJs + Flow

**Comment by zenflow** [comment] 2019-02-22 17:49
Can you share your project? If not, can you please reproduce the problem on one of the above websites, or a GitHub repo?

**Comment by blacksmoke26** [comment] 2019-02-24 12:40
I will try to reproduce, maybe CodeSandBox will be useful to share code.
Thanks!

**Comment by zenflow** [comment] 2019-03-15 18:41
@blacksmoke26 any update on this?

**Comment by blacksmoke26** [comment] 2019-03-15 21:29
@zenflow Moved to Webpack, dropped RollupJS due to so many issues.

Thanks! You can close it now!

**Comment by zenflow** [comment] 2019-03-15 21:33
Strange that the problem went away when you dropped Rollup.. 

I'm thinking this could still be a valid issue (when using Rollup, but not when using Webpack or Parcel), but we have no reproduction.. @limonte what would you do here?

**Comment by limonte** [comment] 2019-03-15 22:31
It might be a valid issue, but I'd still wait for some effort from the community with the reproduction. We can keep the issue opened so people will find it easier when they will stumble upon the same problem.

**Comment by blacksmoke26** [comment] 2019-03-16 23:34
Finally reproduced:

```
index.js:7 Uncaught TypeError: MySwal.fire is not a function
    at index.js:7
    at index.js:7
```
Note: I assume that you have installed gulp globally.

Steps to reproduce:
- Please extract the ([swal-error-produce.zip](https://github.com/sweetalert2/sweetalert2-react-content/files/2974593/swal-error-produce.zip)) zip file somewhere .
- Run `npm install` to install packages.
- Run `npm run rollup` or `gulp rollup/build` to compile the source.
- Open `build/index.html` in a browser (localhost in case)
- See console for more errors



You can skip above and download the following zip file (contains compiled version) to test:
[build-files.zip](https://github.com/sweetalert2/sweetalert2-react-content/files/2974594/build-files.zip)

P.S. Please let me know if you need more details.

**Comment by zenflow** [comment] 2019-03-16 23:38
Thank you very much for your contribution @blacksmoke26 .. I will review this and track down the problem first chance I get

**Comment by zenflow** [comment] 2019-04-06 13:02
Ok, well it's not a bug in `sweetalert2-react-content`, because if you take the reproduction and replace the contents of `src/index.js` with this:

```js
class SomeClass {
	static someStaticMethod () {
		alert('ok')
	}
}
class SomeSubClass extends SomeClass {}
SomeSubClass.someStaticMethod('ok');
```

... we get a very similar error: `Uncaught TypeError: SomeSubClass.someStaticMethod is not a function`.

It's a bug in rollup, but it was fixed a long time ago. 

The reason it was coming up here is because the `rollup-stream` package used here has a [hard dependency on rollup@^0.49.2](https://github.com/Permutatrix/rollup-stream/blob/150aba86920df5469d38d4145c56229538bf7491/package.json#L24). 

Don't use that package.

**Closed by zenflow** 2019-04-06 13:02 UTC
