### ISSUE TITLE
swal does not rerender when the state is changed

### ISSUE THREAD

**Issue by LorhanSohaky** [sweetalert2/sweetalert2-react-content#162] opened 2021-04-24 23:48 UTC
![bug-sweetalert](https://user-images.githubusercontent.com/16273730/115975810-75edb480-a53e-11eb-91a4-78f6ac221f12.gif)

https://codesandbox.io/s/bug-sweetalert-react-y763q

**Comment by shubh27842** [comment] 2021-05-24 09:16
Any update in this issue???
even i am facing same problem while updating quantity

**Comment by ant-fx** [comment] 2021-05-24 10:54
You need to wrap your content in a React component to get state working. Take a look at this closed issue:

https://github.com/sweetalert2/sweetalert2-react-content/issues/52

For example, instead of this:

```javascript
ReactSwal.fire({
  html: (
    <input type="text" value={value} />
  )
 })
```

You would have something like this:

```javascript

const Component = (props) => {
  const [value, setValue] = useState('');
  return (
    <input
      type="text"
      value={value}
      onChange={(e) => {
        setValue(e.target.value);
      }
    />
  );
}

ReactSwal.fire({
  html: (
    <Component />
  )
 })
```

**Comment by shubh27842** [comment] 2021-05-26 06:58
> You need to wrap your content in a React component to get state working. Take a look at this closed issue:
> 
> #52
> 
> For example, instead of this:
> 
> ```js
> ReactSwal.fire({
>   html: (
>     <input type="text" value={value} />
>   )
>  })
> ```
> 
> You would have something like this:
> 
> ```js
> const Component = (props) => {
>   const [value, setValue] = useState('');
>   return (
>     <input
>       type="text"
>       value={value}
>       onChange={(e) => {
>         setValue(e.target.value);
>       }
>     />
>   );
> }
> 
> ReactSwal.fire({
>   html: (
>     <Component />
>   )
>  })
> ```

thank you

**Comment by LorhanSohaky** [comment] 2021-05-27 01:12
@ant-fx , but how to expose the state to outside the component?

**Comment by zenflow** [comment] 2021-05-27 20:22
> how to expose the state to outside the component?

@LorhanSohaky Maybe there will be some better suggestion, but I have one: 

```diff
const Component = (props) => {
  const [value, setValue] = useState('');
  return (
    <input
      type="text"
      value={value}
      onChange={(e) => {
        setValue(e.target.value);
+       props.onValue(e.target.value);
      }
    />
  );
}
// ...
const openPopup = async () => {
+ let popupData = '';
  const { isConfirmed } = await ReactSwal.fire({
    html: (
-      <Component />
+      <Component onValue={value => { popupData = value }} />
  )

  if (isConfirmed) {
    await submitDate(popupData)
  }
 })
}
```

**Comment by zenflow** [comment] 2021-05-31 02:50
@LorhanSohaky Do you have a comment about my suggested solution? Or just the 👀 emoji? Does it not work?

**Comment by zenflow** [comment] 2021-05-31 03:11
Closing this because 
1. The original stated issue ("swal does not rerender when the state is changed") is invalid. You have to encapsulate state in a component, as @ant-fx shared here https://github.com/sweetalert2/sweetalert2-react-content/issues/162#issuecomment-846960762 .. thanks @ant-fx!
2. The follow up issue (about getting that data out of component state when the popup is closed) has a suggested solution here https://github.com/sweetalert2/sweetalert2-react-content/issues/162#issuecomment-849915971

@LorhanSohaky You're welcome

**Closed by zenflow** 2021-05-31 03:11 UTC

**Comment by meotimdihia** [comment] 2021-07-06 17:02
This seems complicated, do we have easy solutions? example: `react-modal` worked with simple wrapping.

**Comment by LorhanSohaky** [comment] 2021-07-12 01:17
> @LorhanSohaky Do you have a comment about my suggested solution? Or just the eyes emoji? Does it not work?

Its work for me, tks

**Comment by ramilamparo** [comment] 2021-09-28 07:25
I am late to the party but I hope this can help someone.
You can use React Portal to render items inside the modal content.

[Sandbox Link.](https://codesandbox.io/s/sweetalertportal-1myd7?file=/src/SweetAlert2.js)

```javascript
import Swal from "sweetalert2";
import { createPortal } from "react-dom";
import withReactContent from "sweetalert2-react-content";
import { useEffect, useState } from "react";

const MySwal = withReactContent(Swal);

const SweetAlert2 = ({ children, show, onClose }) => {
  const [container, setContainer] = useState(null);

  useEffect(() => {
    if (show) {
      MySwal.fire({
        html: <div ref={(el) => setContainer(el)} className="asdfasdf" />
      }).then(() => {
        onClose && onClose();
      });
    }
  }, [show, onClose]);

  useEffect(() => {}, [container, children]);

  if (container) {
    return createPortal(children, container);
  }
  return null;
};

export default SweetAlert2;
```

**Comment by LorhanSohaky** [comment] 2021-09-28 11:26
@ramilamparo Did not know this function, very cool!

**Comment by shaiozfize** [comment] 2023-07-02 08:04
> I am late to the party but I hope this can help someone. You can use React Portal to render items inside the modal content.
> 
> [Sandbox Link.](https://codesandbox.io/s/sweetalertportal-1myd7?file=/src/SweetAlert2.js)
> 
> ```js
> import Swal from "sweetalert2";
> import { createPortal } from "react-dom";
> import withReactContent from "sweetalert2-react-content";
> import { useEffect, useState, useCallback } from "react";
> 
> function App() {
>   const [shown, setShown] = useState(false);
>   const [value, setValue] = useState("");
> 
>   const handleClick = useCallback(function handleClick() {
>     setShown(true);
>   }, []);
> 
>   const handleClose = useCallback(function handleClose() {
>     setShown(false);
>   }, []);
> 
>   const handleChange = useCallback(function handleChange(e) {
>     setValue(e.target.value);
>   }, []);
> 
>   return (
>     <div>
>       <h1>{value}</h1>
>       <button onClick={handleClick}>Alert</button>
>       <SweetAlert2 show={shown} onClose={handleClose}>
>         <input onChange={handleChange} value={value} />
>       </SweetAlert2>
>     </div>
>   );
> }
> 
> const MySwal = withReactContent(Swal);
> 
> const SweetAlert2 = ({ children, show, onClose }) => {
>   const [container, setContainer] = useState(null);
> 
>   useEffect(() => {
>     if (show) {
>       MySwal.fire({
>         html: <div ref={(el) => setContainer(el)} />
>       }).then(() => {
>         onClose && onClose();
>       });
>     }
>   }, [show, onClose]);
> 
>   if (container) {
>     return createPortal(children, container);
>   }
>   return null;
> };
> ```

@ramilamparo 
Nice! but using this showLoaderOnConfirm stopped working for me... (even though preConfirm does work!) does this reproduce for you also? any advice???
