### ISSUE TITLE
Error: m.createRoot is not a function

### ISSUE THREAD

**Issue by itsmdsameerkhan** [sweetalert2/sweetalert2-react-content#198] opened 2022-06-17 09:37 UTC
<img width="541" alt="image" src="https://user-images.githubusercontent.com/46621885/174271884-51c96aa1-1701-44dc-a1a0-273d30ed4179.png">

**Comment by limonte** [comment] 2022-06-17 10:31
Duplicate of #197

**Closed by limonte** 2022-06-17 10:31 UTC
