### ISSUE TITLE
What set of JSX does this support?

### ISSUE THREAD

**Issue by GreenAsJade** [sweetalert2/sweetalert2-react-content#200] opened 2022-06-19 11:52 UTC
I tried to do

```
Swal.fire({
    text: "test",
    footer: <Link to={"/"}>Test link</Link>
```

and the footer is rendered empty.

`Link` comes from react-router-dom.

**Comment by limonte** [comment] 2022-06-19 12:19
Duplicate of #194

**Closed by limonte** 2022-06-19 12:19 UTC
